export const descriptionMap: Record<string, string> = {
  environment: "The environment to which the request should be sent.",
  clientKey: "The client key used to authenticate requests from your website.",
  paymentMethodsResponse: "The response from the /paymentMethods endpoint.",
  paymentMethodsConfiguration:
    "The configuration object for the payment methods.",
  locale: "The shopper's locale. For example, `en-US`.",
  translations: "The translations object.",
  amount: "The transaction amount.",
  countryCode: "The shopper's country code.",
  allowPaymentMethods: "The payment methods to be shown.",
  removePaymentMethods: "The payment methods to be hidden.",
  loadingContext: "The URL to the Adyen Checkout API.",
  analytics: "The configuration object for the analytics module.",
  risk: "The configuration object for the risk module.",
  session: "The session object.",
  id: "The unique identifier for the payment session.",
  originKey: "The origin key used to authenticate requests from your website.",
  sessionData: "The session data object.",
  shopperEmail: "The shopper's email address.",
  telephoneNumber: "The shopper's telephone number.",
  showPayButton: "Whether to show the pay button.",
  secondaryAmount: "The secondary amount.",
  srConfig: "The configuration object for the secure redirect module.",
  order: "The order object.",
  exposeLibraryMetadata: "Whether to expose library metadata.",
  beforeRedirect: "The function to call before redirecting the shopper.",
  beforeSubmit: "The function to call before submitting the payment details.",
  onPaymentCompleted: "The function to call when the payment is completed.",
  onPaymentFailed: "The function to call when the payment fails.",
  onSubmit: "The function to call when the payment details are submitted.",
  onAdditionalDetails:
    "The function to call when additional details are required.",
  onActionHandled: "The function to call when the action is handled.",
  onChange: "The function to call when the state changes.",
  onError: "The function to call when an error occurs.",
  onReady: "The function to call when the component is ready.",
  onBalanceCheck: "The function to call when the balance is checked.",
  onOrderRequest: "The function to call when the order is requested.",
  onEnterKeyPressed: "The function to call when the enter key is pressed.",
  onPaymentMethodsRequest:
    "The function to call when the payment methods are requested.",
  onOrderCancel: "The function to call when the order is canceled.",
  onOrderUpdated: "The function to call when the order is updated.",
};
